
driver:	driver.cpp Shape.cpp Triangle.cpp Circle.cpp Quadrilateral.cpp Color.cpp Header.cpp Point.cpp
	g++ -Wall driver.cpp Shape.cpp Triangle.cpp Circle.cpp Quadrilateral.cpp Color.cpp Header.cpp Point.cpp -o driver

run:	driver
	./driver input.txt testoutput.ppm

clean:
	rm driver
	
